#             __________               __   ___.
#   Open      \______   \ ____   ____ |  | _\_ |__   _______  ___
#   Source     |       _//  _ \_/ ___\|  |/ /| __ \ /  _ \  \/  /
#   Jukebox    |    |   (  <_> )  \___|    < | \_\ (  <_> > <  <
#   Firmware   |____|_  /\____/ \___  >__|_ \|___  /\____/__/\_ \
#                     \/            \/     \/    \/            \/
# $Id: Makefile 21844 2009-07-13 18:39:11Z dave $
#

all: flashsplit

flashsplit: flashsplit.c
	gcc -W -Wall -o flashsplit flashsplit.c

clean:
	rm -f flashsplit
